### ISSUE TITLE
Can't hide app in app drawer

### ISSUE THREAD

**Issue by jiggs82** [KieronQuinn/PixelLauncherMods#1]
Can't hide apps in the app drawer, says it failed. P6Pro a13 dp2 

https://drive.google.com/file/d/1GM8nb-VdjO6AP0S2A-VOsxt4vMr0oYlR/view?usp=drivesdk

**Comment by KieronQuinn** [comment]
Fixed in 2.0.1, thanks for the log.

No idea at what point that broke, it was definitely working last week when I clean installed 13 DP2. Apologies!

**Comment by jiggs82** [comment]
Oh ok well it now works with v. 2.0.1 and glad I could help 👍🏻
