### ISSUE TITLE
Is there a way to call "Re-apply Icons" externally?

### ISSUE THREAD

**Issue by GoodbyeNJN** [KieronQuinn/PixelLauncherMods#105]
I would like to automatically reapply icons by some other automated task.

Currently I found a method which is `adb shell am start -a android.intent.action.VIEW -d plm://reapply`, but this method will bring the application to foreground, and I just want to run it in background without awareness.

Is it possible to provide such a method?

**Comment by KieronQuinn** [comment]
Added in 2.5, although it's undocumented. Action is `com.kieronquinn.app.pixellaunchermods.action.REAPPLY`.

**Comment by GoodbyeNJN** [comment]
> Added in 2.5, although it's undocumented. Action is `com.kieronquinn.app.pixellaunchermods.action.REAPPLY`.

Could you give an example? I'm not sure how to use it.
