### ISSUE TITLE
Some questions about Hide Clock

### ISSUE THREAD

**Issue by LY98729** [KieronQuinn/PixelLauncherMods#108]
![Screenshot_20230616-104254](https://github.com/KieronQuinn/PixelLauncherMods/assets/128117522/57f3c86c-d94a-474d-843e-a6a844e4e29e)
This option kills my time display and I can't restore my time display by restarting systemUI or restarting the phone or revoking root access to the app.

**Comment by KieronQuinn** [comment]
#10
