### ISSUE TITLE
When I change the wallpaper, the color of the icons in the drawer will not change with the wallpaper change, only the desktop icons will change with the wallpaper

### ISSUE THREAD

**Issue by Suxingcheng** [KieronQuinn/PixelLauncherMods#109]
When I change the wallpaper, the color of the icons in the drawer will not change with the wallpaper change, only the desktop icons will change with the wallpaper

**Comment by KieronQuinn** [comment]
This is normal. You have to re-apply the icons.

**Comment by Suxingcheng** [comment]
> This is normal. You have to re-apply the icons. 

I clicked the reapply icon and swiped, and restarted the phone, the color of the icon in the drawer is still the color of the previous wallpaper
