### ISSUE TITLE
Hey not rly an issue but idk where to put it 

### ISSUE THREAD

**Issue by NathanLL** [KieronQuinn/PixelLauncherMods#112]
Hey ! Got an idea for u, its for the navigation bar, can u try idk if this possible to put an function in ur app to remove or disable de navigation bar ? That will be great !

Thanks for taking ur time in reading this, have an nice day or night !

**Comment by KieronQuinn** [comment]
Which navigation bar?

**Comment by NathanLL** [comment]
Hey its the google one ill put an screen 
![Uploading Screenshot_20230715-005145.png…]()

**Comment by NathanLL** [comment]
The one at the bottom of the screen

**Comment by KieronQuinn** [comment]
That screenshot didn't finish uploading, try again please

**Comment by NathanLL** [comment]
![Screenshot_20230715-005145](https://github.com/KieronQuinn/PixelLauncherMods/assets/70818764/2c7b7c80-54b3-4b9e-8c25-0e8a4c81674c)

**Comment by NathanLL** [comment]
U see it now ?

**Comment by KieronQuinn** [comment]
You can already replace this with the Search Box replacement option.
