### ISSUE TITLE
[Request] Remove app labels

### ISSUE THREAD

**Issue by fillwithjoy1** [KieronQuinn/PixelLauncherMods#116]
Can you try and mirror something similar to Nothing's launcher, as I really love that apps with no icon labels.

**Comment by KieronQuinn** [comment]
Not possible unfortunately

**Comment by fillwithjoy1** [comment]
> Not possible unfortunately

Oh ok

**Comment by lewisdoesstuff** [comment]
Hi! 
Just found a workaround for this:

While it doesn't allow you to input a blank label (just defaults to the standard label), you can use a Unicode "Braille Pattern Blank" character, and it'll hide the label.

Copy it from [here](https://www.compart.com/en/unicode/U+2800)

Not sure if it'd be possible to add a "Hide label" option that can set this for us? @KieronQuinn
