### ISSUE TITLE
[Request] Force themed icons on all apps

### ISSUE THREAD

**Issue by fillwithjoy1** [KieronQuinn/PixelLauncherMods#117]
Can we get a toggle to force themed icons on all apps. 
Maybe this news post will help: https://www.xda-developers.com/google-testing-automatic-themed-icons-pixel-launcher/

**Comment by Jnss98b** [comment]
You can also already generate themed icon for any app on android 13 too so it would be nice to have an "enable all" toggle instead of having to doing it one app at a time like how it is right now

**Comment by Jnss98b** [comment]
> > You can also already generate themed icon for any app on android 13 too so it would be nice to have an "enable all" toggle instead of having to doing it one app at a time like how it is right now
> 
> That's not stock, at least not without the test flag mentioned in the OP.

I actually meant this option in your app

![Screenshot_20230816-164732](https://github.com/KieronQuinn/PixelLauncherMods/assets/24306400/992a4514-7356-4944-91a1-943abb690f38)
![Screenshot_20230816-164728](https://github.com/KieronQuinn/PixelLauncherMods/assets/24306400/43033561-1bd2-4616-ae08-a04c59cd2558)

**Comment by Jnss98b** [comment]
Right now if you wanna take advantage that, you'd have to do one app at a time
![Screenshot_20230816-164835](https://github.com/KieronQuinn/PixelLauncherMods/assets/24306400/5699bd42-d7ce-43f4-a32d-73ad940e7400)

**Comment by fillwithjoy1** [comment]
Yeah, something like that. Just want to enable themed app icons for all apps, even unsupported ones

**Comment by KieronQuinn** [comment]
That's intentional. The whole point of having users (you) apply it to each app is so you approve them, because otherwise there's going to be people who do not realise that an app's icon was changed during the application, it looks crap (as many do), and complain to the actual app's developer. 

This has been my stance since the beginning, and it won't change until Google start forcing themed icons.

**Comment by fillwithjoy1** [comment]
> 

Alright, I get you. You know any other resources that could help at least?

**Comment by KieronQuinn** [comment]
Keep an eye on the GappsMod Flags Telegram channel, the launcher flag might become available again at some point: https://t.me/GappsModFlags

**Comment by niksingh710** [comment]
https://www.reddit.com/r/Android/comments/13wrktx/a_look_at_androids_hidden_forced_themed_icon/

seeing this is there any way to add a toggle that can enable the developer flag `ENABLE_FORCED_MONO_ICON`? Many croms seems to give this option.

**Comment by fillwithjoy1** [comment]
> https://www.reddit.com/r/Android/comments/13wrktx/a_look_at_androids_hidden_forced_themed_icon/
> 
> seeing this is there any way to add a toggle that can enable the developer flag `ENABLE_FORCED_MONO_ICON`? Many croms seems to give this option.

Use PixelXpert
