### ISSUE TITLE
[Request] Option to fix widget reload bug on Android 12

### ISSUE THREAD

**Issue by 44ron** [KieronQuinn/PixelLauncherMods#118]
So I don't know if this is even possible to fix at all, but Pixel Launcher 12 has a bug where if I enter any app and switch to landscape mode via auto or manual rotation, the widgets on the homescreen disappear from memory and reload the next time I open the homescreen.
As far as I know, there are no known fixes for this except for updating to Android 13, which is not an option for me.
Is this something that can be fixed through PLM, which I use anyway? If yes, I'd really appreciate an option in PLM that patches this issue.

**Comment by KieronQuinn** [comment]
No, this is not something I can fix
