### ISSUE TITLE
[Request] An option to open hidden apps from the PLM app itself

### ISSUE THREAD

**Issue by Username1-a** [KieronQuinn/PixelLauncherMods#119]
Hello, maybe you'll find it worthwhile – just would be more convenient and quicker to be at least able to open the hidden apps from the "Pixel Launcher Mods" itself, if other methods are difficult to implement and requre Xposed – maybe, if possible, adding to PLM like a separate tab/page with hidden apps mimicking launcher's app drawer/folder

**Comment by KieronQuinn** [comment]
Covered in #114
