### ISSUE TITLE
It keeps crashing

### ISSUE THREAD

**Issue by nonyonah** [KieronQuinn/PixelLauncherMods#12]
The app keeps crashing. I tried to theme an unthemed icon and it crashed, since then whenever I tried to go back to the app it crashes.

**Comment by EXOTICdummyy** [comment]
> The app keeps crashing. I tried to theme an unthemed icon and it crashed, since then whenever I tried to go back to the app it crashes.

The app doesn't open at all, keeps crashing again and again

**Comment by KieronQuinn** [comment]
Please provide a crash log, a report like this is absolutely useless without one.

**Comment by Issam28** [comment]
> The app doesn't open at all, keeps crashing again and again

It doesn't open for me when I'm not connected to the internet, I don't know what might be causing the issue.

**Comment by KieronQuinn** [comment]
Fixed in 2.1
