### ISSUE TITLE
[Feature request] Putting folders inside another folder

### ISSUE THREAD

**Issue by Jnss98b** [KieronQuinn/PixelLauncherMods#120]
Ok, this is a pretty crazy request but I just wanted to ask in case it's possible. How about a mod that lets you put a folder inside of another folder? I don't really need some crazy inception stuff so just 1 level deep is fine. Would this be technically possible at all?

Inspiration came from this app but I wanted something more native and the way that app displays folders doesn't look good and looks out of place among other folders
https://play.google.com/store/apps/details?id=com.ss.folderinfolder

**Comment by KieronQuinn** [comment]
Not possible as an overlay.

**Comment by Jnss98b** [comment]
Aww what a shame
