### ISSUE TITLE
Wallpaper Scrim option not working (A14 QPR1 Beta)

### ISSUE THREAD

**Issue by cybr47** [KieronQuinn/PixelLauncherMods#122]
I'm using A14 on my Pixel 7 Pro. I enabled the option to remove the status bar shadow but it doesn't work and I still have that shadow. I looked into the Overlay apk which PLM creates and tried copying the stuff to Pixel Launcher but it still didn't work. I'm unable to use my fav dark wallpaper cuz of this ugly shadow google decided to force on every user just like At a glance.

![Screenshot_20230920-212128](https://github.com/KieronQuinn/PixelLauncherMods/assets/81064836/f9c44288-4b10-45ad-9ac5-c45d40022c24)

**Comment by KieronQuinn** [comment]
Unfortunately this is no longer possible for an overlay, so the option will be disabled in the next update for Android 14+
