### ISSUE TITLE
App not starting at boot

### ISSUE THREAD

**Issue by regix1** [KieronQuinn/PixelLauncherMods#124]
Hi,

for anyone else frustrated with the app not launching whenever you reboot your phone. You can use this command to run the service at boot:

`am startservice com.kieronquinn.app.pixellaunchermods/.service.PixelLauncherModsForegroundService`

I run it with MacroDroid or you could probably find a guide online for crond.

**Comment by KieronQuinn** [comment]
Fixed in 2.6
