### ISSUE TITLE
the app crashes every time

### ISSUE THREAD

**Issue by thepyrite** [KieronQuinn/PixelLauncherMods#125]
i dont know if its only for stock android but im on the latest lineageOS 20 and the app crashes each time i try to launch it.

**Comment by KieronQuinn** [comment]
Please post a logcat.

**Comment by regix1** [comment]
I don't have the crashing issue and I'm using the Pixel 7 Pro, it's probably just lineageOS

**Comment by KieronQuinn** [comment]
Does the Lineage device actually have the Pixel Launcher installed?

**Comment by thepyrite** [comment]
ok so i figured that it doesnt work with the lineageOS default pixel launcher but it does work with Pixel Launcher Extended so technically my issue has been solved. But the thing is that the lineage os default launcher is just the regular pixel launcher without the search bar and extra minor features so it should've technically worked as intended but yeah.

**Comment by KieronQuinn** [comment]
> ok so i figured that it doesnt work with the lineageOS default pixel launcher but it does work with Pixel Launcher Extended so technically my issue has been solved. But the thing is that the lineage os default launcher is just the regular pixel launcher without the search bar and extra minor features so it should've technically worked as intended but yeah.

The lineage launcher is different and not compatible
