### ISSUE TITLE
[REQUEST]

### ISSUE THREAD

**Issue by Fefedu973** [KieronQuinn/PixelLauncherMods#127]
In the icon pack section add the ability to use Android themed icon as an icon pack to use icons packs apps only to "fill the gabs" of the default Android themed icons

**Comment by KieronQuinn** [comment]
You already can use themed icons as app drawer icons, they just have to be done individually. The way they work is different to the way normal icon packs work so it wouldn't easily be possible to treat them as a normal icon pack.
