### ISSUE TITLE
[REQUEST] Add the ability to remove shortcut badges (as Google removed the widget workaround for apps like shortcut maker)

### ISSUE THREAD

**Issue by Fefedu973** [KieronQuinn/PixelLauncherMods#129]
![Screenshot_20231027-194540~2.png](https://github.com/KieronQuinn/PixelLauncherMods/assets/80718477/226c4728-d921-4b20-a3e4-a7f47957c8a9)

**Comment by KieronQuinn** [comment]
Doesn't seem to be possible. The badge is rendered into the icon at runtime, and its size is hardcoded.

**Comment by Fefedu973** [comment]
> Doesn't seem to be possible. The badge is rendered into the icon at runtime, and its size is hardcoded.

Hum... Ok thanks anyway for the quick reply!
