### ISSUE TITLE
Sometimes when the icon is changed it doesn't fit nicely 

### ISSUE THREAD

**Issue by Fefedu973** [KieronQuinn/PixelLauncherMods#130]
This is just an example but I got this issue many times (not always as zoomed in as this but sometimes enough to be cropped on the edges)https://github.com/KieronQuinn/PixelLauncherMods/assets/80718477/368590b2-55bb-41bc-936f-5a78870a7205

**Comment by Fefedu973** [comment]
Another exemple
https://github.com/KieronQuinn/PixelLauncherMods/assets/80718477/96699336-e30c-4431-bd08-9648561f52b7

**Comment by KieronQuinn** [comment]
Duplicate of #74
