### ISSUE TITLE
 Unable to create application com.kieronquinn.app.pixellaunchermods.PixelLauncherMods

### ISSUE THREAD

**Issue by alabotski** [KieronQuinn/PixelLauncherMods#133]
I have Pixel 7 Pro with root
With latest crDroid firmware, https://crdroid.net/cheetah/9

When I launch [PixelLauncherMods](https://github.com/KieronQuinn/PixelLauncherMods) 2.5
This error appears https://paste.crdroid.net/6rlqRa

**Comment by KieronQuinn** [comment]
You don't have the Pixel Launcher installed.
