### ISSUE TITLE
Crash in moto edge 40 Neo (Android 13)

### ISSUE THREAD

**Issue by lkrjangid1** [KieronQuinn/PixelLauncherMods#134]
- When I try to open app after install it's crash.

**Comment by KieronQuinn** [comment]
Do you have the Pixel Launcher (**not** Pixel Launcher Mods) installed? If you do, provide a log.

**Comment by KieronQuinn** [comment]
No response, assuming you don't have the Pixel Launcher installed. Closing.

**Comment by lkrjangid1** [comment]
Logs:
"""
11-28 16:32:29.160  1827  1827 E AndroidRuntime: FATAL EXCEPTION: main
11-28 16:32:29.160  1827  1827 E AndroidRuntime: Process: com.kieronquinn.app.pixellaunchermods, PID: 1827
11-28 16:32:29.160  1827  1827 E AndroidRuntime: java.lang.RuntimeException: Unable to create application com.kieronquinn.app.pixellaunchermods.PixelLauncherMods: org.koin.core.error.InstanceCreationException: Could not create instance for '[Singleton:'com.kieronquinn.app.pixellaunchermods.repositories.RemoteAppsRepository']'
11-28 16:32:29.160  1827  1827 E AndroidRuntime:        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6953)
11-28 16:32:29.160  1827  1827 E AndroidRuntime:        at android.app.ActivityThread.-$$Nest$mhandleBindApplication(Unknown Source:0)
11-28 16:32:29.160  1827  1827 E AndroidRuntime:        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2224)
11-28 16:32:29.160  1827  1827 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:111)
11-28 16:32:29.160  1827  1827 E AndroidRuntime:        at android.os.Looper.loopOnce(Looper.java:238)
11-28 16:32:29.160  1827  1827 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:357)
11-28 16:32:29.160  1827  1827 E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:8109)
11-28 16:32:29.160  1827  1827 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
11-28 16:32:29.160  1827  1827 E AndroidRuntime:        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
11-28 16:32:29.160  1827  1827 E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:957)
11-28 16:32:29.160  1827  1827 E AndroidRuntime: Caused by: org.koin.core.error.InstanceCreationException: Could not create instance for '[Singleton:'com.kieronquinn.app.pixellaunchermods.repositories.RemoteAppsRepository']'
11-28 16:32:29.160  1827  1827 E AndroidRuntime:        at org.koin.core.instance.InstanceFactory.create(InstanceFactory.kt:58)
11-28 16:32:29.160  1827  1827 E AndroidRuntime:        at org.koin.core.instance.SingleInstanceFactory.create(SingleInstanceFactory.kt:46)
11-28 16:32:29.160  1827  1827 E AndroidRuntime:        at org.koin.core.instance.SingleInstanceFactory$get$1.invoke(SingleInstanceFactory.kt:53)
11-28 16:32:29.160  1827  1827 E AndroidRuntime:        at org.koin.core.instance.SingleInstanceFactory$get$1.invoke(SingleInstanceFactory.kt:51)
11-28 16:32:29.160  1827  1827 E AndroidRuntime:        at org.koin.mp.KoinPlatformTools.synchronized(KoinPlatformTools.kt:20)
11-28 16:32:29.160  1827  1827 E AndroidRuntime:        at org.koin.core.instance.SingleInstanceFactory.get(SingleInstanceFactory.kt:51)
11-28 16:32:29.160  1827  1827 E AndroidRuntime:        at org.koin.core.registry.InstanceRegistry.createEagerInstances(InstanceRegistry.kt:96)
11-28 16:32:29.160  1827  1827 E AndroidRuntime:        at org.koin.core.registry.InstanceRegistry.createAllEagerInstances$koin_core(InstanceRegistry.kt:64)
11-28 16:32:29.160  1827  1827 E AndroidRuntime:        at org.koin.core.Koin.createEagerInstances(Koin.kt:323)
11-28 16:32:29.160  1827  1827 E AndroidRuntime:        at org.koin.core.KoinApplication.createEagerInstances(KoinApplication.kt:74)
11-28 16:32:29.160  1827  1827 E AndroidRuntime:        at org.koin.core.context.GlobalContext.startKoin(GlobalContext.kt:66)
11-28 16:32:29.160  1827  1827 E AndroidRuntime:        at org.koin.core.context.DefaultContextExtKt.startKoin(DefaultContextExt.kt:40)
11-28 16:32:29.160  1827  1827 E AndroidRuntime:        at com.kieronquinn.app.pixellaunchermods.PixelLauncherMods.onCreate(PixelLauncherMods.kt:189)
11-28 16:32:29.160  1827  1827 E AndroidRuntime:        at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1279)
11-28 16:32:29.160  1827  1827 E AndroidRuntime:        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6948)
11-28 16:32:29.160  1827  1827 E AndroidRuntime:        ... 9 more
11-28 16:32:29.160  1827  1827 E AndroidRuntime: Caused by: org.koin.core.error.InstanceCreationException: Could not create instance for '[Singleton:'com.kieronquinn.app.pixellaunchermods.repositories.IconLoaderRepository']'
11-28 16:32:29.160  1827  1827 E AndroidRuntime:        at org.koin.core.instance.InstanceFactory.create(InstanceFactory.kt:58)
11-28 16:32:29.160  1827  1827 E AndroidRuntime:        at org.koin.core.instance.SingleInstanceFactory.create(SingleInstanceFactory.kt:46)
11-28 16:32:29.160  1827  1827 E AndroidRuntime:        at org.koin.core.instance.SingleInstanceFactory$get$1.invoke(SingleInstanceFactory.kt:53)
11-28 16:32:29.160  1827  1827 E AndroidRuntime:        at org.koin.core.instance.SingleInstanceFactory$get$1.invoke(SingleInstanceFactory.kt:51)
11-28 16:32:29.160  1827  1827 E AndroidRuntime:        at org.koin.mp.KoinPlatformTools.synchronized(KoinPlatformTools.kt:20)
11-28 16:32:29.160  1827  1827 E AndroidRuntime:        at org.koin.core.instance.SingleInstanceFactory.get(SingleInstanceFactory.kt:51)
11-28 16:32:29.160  1827  1827 E AndroidRuntime:        at org.koin.core.registry.InstanceRegistry.resolveInstance$koin_core(InstanceRegistry.kt:116)
11-28 16:32:29.160  1827  1827 E AndroidRuntime:        at org.koin.core.scope.Scope.resolveValue(Scope.kt:246)
11-28 16:32:29.160  1827  1827 E AndroidRuntime:        at org.koin.core.scope.Scope.resolveInstance(Scope.kt:231)
11-28 16:32:29.160  1827  1827 E AndroidRuntime:        at org.koin.core.scope.Scope.get(Scope.kt:210)
11-28 16:32:29.160  1827  1827 E AndroidRuntime:        at com.kieronquinn.app.pixellaunchermods.PixelLauncherMods$repositories$1$3.invoke(PixelLauncherMods.kt:210)
11-28 16:32:29.160  1827  1827 E AndroidRuntime:        at com.kieronquinn.app.pixellaunchermods.PixelLauncherMods$repositories$1$3.invoke(PixelLauncherMods.kt:117)
11-28 16:32:29.160  1827  1827 E AndroidRuntime:        at org.koin.core.instance.InstanceFactory.create(InstanceFactory.kt:51)
11-28 16:32:29.160  1827  1827 E AndroidRuntime:        ... 23 more
11-28 16:32:29.160  1827  1827 E AndroidRuntime: Caused by: android.content.pm.PackageManager$NameNotFoundException: com.google.android.apps.nexuslauncher
11-28 16:32:29.160  1827  1827 E AndroidRuntime:        at android.app.ApplicationPackageManager.getApplicationInfoAsUser(ApplicationPackageManager.java:504)
11-28 16:32:29.160  1827  1827 E AndroidRuntime:        at android.app.ApplicationPackageManager.getApplicationInfo(ApplicationPackageManager.java:487)
11-28 16:32:29.160  1827  1827 E AndroidRuntime:        at android.app.ApplicationPackageManager.getApplicationInfo(ApplicationPackageManager.java:481)
11-28 16:32:29.160  1827  1827 E AndroidRuntime:        at android.app.ApplicationPackageManager.getResourcesForApplication(ApplicationPackageManager.java:2048)
11-28 16:32:29.160  1827  1827 E AndroidRuntime:        at com.kieronquinn.app.pixellaunchermods.utils.extensions.Extensions_ContextKt.createPixelLauncherResources(Extensions+Context.kt:50)
11-28 16:32:29.160  1827  1827 E AndroidRuntime:        at com.kieronquinn.app.pixellaunchermods.repositories.IconLoaderRepositoryImpl.<init>(IconLoaderRepository.kt:112)
11-28 16:32:29.160  1827  1827 E AndroidRuntime:        at com.kieronquinn.app.pixellaunchermods.repositories.IconLoaderRepositoryImpl.<init>(IconLoaderRepository.kt:90)
11-28 16:32:29.160  1827  1827 E AndroidRuntime:        at com.kieronquinn.app.pixellaunchermods.PixelLauncherMods$repositories$1$5.invoke(PixelLauncherMods.kt:119)
11-28 16:32:29.160  1827  1827 E AndroidRuntime:        at com.kieronquinn.app.pixellaunchermods.PixelLauncherMods$repositories$1$5.invoke(PixelLauncherMods.kt:119)
11-28 16:32:29.160  1827  1827 E AndroidRuntime:        at org.koin.core.instance.InstanceFactory.create(InstanceFactory.kt:51)
11-28 16:32:29.160  1827  1827 E AndroidRuntime:        ... 35 more
"""

**Comment by KieronQuinn** [comment]
> No response, assuming you don't have the Pixel Launcher installed. Closing.

This is correct, you don't have the Pixel Launcher installed.
