### ISSUE TITLE
[Suggestion] Autogenerate adaptive icons

### ISSUE THREAD

**Issue by gaussandhisgun** [KieronQuinn/PixelLauncherMods#135]
TIL that Pixel Launcher Mods can generate "themed icons" from the application icons if you enable themed icons, go to PLM, tap the app you want a themed icon for, tap the homescreen icon (its a plus sign for apps without a themed icon) and tap the app again. It would be cool if we had a way to automate this for all the apps that dont have a themed icon already, and maybe a switch in the PLM app list to show the themed icons on the apps so we can see which icons were auto-generated wrong and need manual interference.

Yes, I have *that* many apps.

**Comment by KieronQuinn** [comment]
#117
