### ISSUE TITLE
Magisk module installation failed

### ISSUE THREAD

**Issue by RobMann94** [KieronQuinn/PixelLauncherMods#139]
Magisk module installation fails after saving from V2.6 of the app. Latest magisk and pixel 7 pro A14 December.

**Comment by Lyceris-chan** [comment]
I was too lazy to make an issue but yea downgrading the app and creating a module using it and then upgrading works fine here but I'm not on any beta builds of android

**Comment by edricus** [comment]
Magisk Module for 2.6 doesn't work  
Downgrading to 2.5 - Saving the module and then install it works

**Comment by KieronQuinn** [comment]
Should be fixed in 2.6.1. It needs to be built on a Unix based system, I thought I fixed this but apparently not.
