### ISSUE TITLE
Request - icon swipes a la nova launcher

### ISSUE THREAD

**Issue by Zebov** [KieronQuinn/PixelLauncherMods#142]
As nova launcher is the only launcher that supports swiping on icons, with my current setup I'm limited to that singular program. Ideally, I'd like to be able to have this ability with the stock launcher.

**Comment by KieronQuinn** [comment]
Not possible with overlays, ask one of the Xposed based mods.

**Comment by Zebov** [comment]
I sincerely appreciate both you reaching out with info and all of your work!
