### ISSUE TITLE
[Bug] Can't set widget replacement that can be configured 

### ISSUE THREAD

**Issue by srt54558** [KieronQuinn/PixelLauncherMods#144]
Widgets that can be configured (to e.g. select what style to use) can't be set as a replacement unfortunately

**Comment by KieronQuinn** [comment]
Fixed in 2.6.2

**Comment by KieronQuinn** [comment]
> https://streamable.com/a2mcnc
> 
> The issue still persists. The Widgets work in the launcher tho, but not when replacing the search bar

I'd missed one of the calls, fixed in 2.6.3. I've checked with that exact widget and it works now.
