### ISSUE TITLE
Bring back the apply icons shortcut that was removed in a previous update and make it apply in the background instead of opening the app.

### ISSUE THREAD

**Issue by Fefedu973** [KieronQuinn/PixelLauncherMods#148]

**Comment by KieronQuinn** [comment]
The shortcut is still there.

**Comment by Fefedu973** [comment]
> The shortcut is still there.

Yes I just found it again but it was removed at some point but is it possible to re-apply icons without opening the app but re-applying them in the background

**Comment by KieronQuinn** [comment]
No, opening the app is required. The shortcut has never been removed, it's likely your launcher just stopped showing it.

**Comment by Fefedu973** [comment]
> No, opening the app is required. The shortcut has never been removed, it's likely your launcher just stopped showing it. 

Hum it is weird, I use the pixel launcher and one day the shortcut has been removed and I cannot add it back
