### ISSUE TITLE
Add search bars to the Apps and Shortcuts sections

### ISSUE THREAD

**Issue by Jnss98b** [KieronQuinn/PixelLauncherMods#15]
Right now they're purely just scrollable lists with no search bars or even a scroll bar like the one below on the pixel launcher app drawer so it's hard to get to the apps you want to modify

![image](https://user-images.githubusercontent.com/24306400/160740558-acf339b0-71f4-4662-afaf-d049b237b700.png)

**Comment by KieronQuinn** [comment]
Search boxes added in 2.1. Fast scroll doesn't work with collapsing toolbars, so won't be added.
