### ISSUE TITLE
Recents Background Transparency doesn't work

### ISSUE THREAD

**Issue by zxsleebu** [KieronQuinn/PixelLauncherMods#152]
Pixel 6 running latest rooted stock firmware AP1A.240405.002. This feature just doesn't work.

**Comment by KieronQuinn** [comment]
Works for me. Make sure the overlay is installed and functional, do the other overlay tweaks work?

**Comment by zxsleebu** [comment]
That's was very dumb of me. I didn't know that overlay is needed to be installed through magisk. Sorry for this. Also, you can install magisk modules through your app automatically. I've seen this in Repainter app yesterday.

**Comment by HeyItsJono** [comment]
Apologies, but where exactly is this overlay module located?
