### ISSUE TITLE
Feature Request - Add the option to disable search bar

### ISSUE THREAD

**Issue by P13rLu1** [KieronQuinn/PixelLauncherMods#153]
Like it's said in the tilte, the search bat occupies too much space, it would be nice to have an option to remove it and make up for the space that it's left behind

**Comment by KieronQuinn** [comment]
All that is possible is to make it invisible, which you can already do by setting it to the blank widget. Anything beyond that is not possible with overlays.

**Comment by P13rLu1** [comment]
> All that is possible is to make it invisible, which you can already do by setting it to the blank widget. Anything beyond that is not possible with overlays.

Do you know if there is some sort of module that hides that bar?

**Comment by KieronQuinn** [comment]
Not that I know of
