### ISSUE TITLE
Adding widget on home screen broken on a15 beta 4

### ISSUE THREAD

**Issue by jiggs82** [KieronQuinn/PixelLauncherMods#157]
Hi I can't add a widget to the Pixel launcher home screen.

**Comment by KieronQuinn** [comment]
Pixel Launcher Mods does not provide a widget, nor does it provide the option to add a widget, or change anything in that regard. What issue exactly are you seeing?

**Comment by jiggs82** [comment]
I mean when I try to add a widget or the search box in Settings/tweaks in your mod. Nothing gets added. Before beta 4 I was about to add a custom qsb on the home screen.

**Comment by KieronQuinn** [comment]
Seems they've changed the setting which overrides the search widget, should be an easy fix

**Comment by KieronQuinn** [comment]
Fixed in 2.6.5
