### ISSUE TITLE
Custom app icons reset after language change

### ISSUE THREAD

**Issue by glaicodes** [KieronQuinn/PixelLauncherMods#162]
I am on A14,
I was using Turkish as my main language, then I change to English for something then my custom icons were gone, 
then I tried to reset them but it took forever so I closed the app but when I reopened the app it now says "an error occured"

**Comment by KieronQuinn** [comment]
Reboot and re-apply the icons.

**Comment by glaicodes** [comment]
![Screenshot_20240914-233247](https://github.com/user-attachments/assets/c9b662fe-4691-40a8-b1ad-f3ed418a1c87)
didnt work, getting this screen
