### ISSUE TITLE
Apply Google search box abnormality

### ISSUE THREAD

**Issue by ghzxs** [KieronQuinn/PixelLauncherMods#164]
Different from actual widgets and cannot be used

![Screenshot_20241103-010901~2](https://github.com/user-attachments/assets/2a7b45ef-188a-49bb-a553-79a14074f929)
![Screenshot_20241103-012947~2](https://github.com/user-attachments/assets/f14013d7-3454-4b13-9d59-21e12b30399a)

**Comment by KieronQuinn** [comment]
This is a widget compatibility issue which cannot be fixed. There's already a warning in the app about this.
