### ISSUE TITLE
Mod broken on A15 qpr2 beta 1

### ISSUE THREAD

**Issue by jiggs82** [KieronQuinn/PixelLauncherMods#168]
Hi, it seems the mod isn't working with a15 qpr2 beta 1 that dropped today. I'm getting Pixel launcher forced stops and it breaks gestures. 

Once uninstalled. Pixel launcher and gestures work again.

Thanks

**Comment by KieronQuinn** [comment]
The Pixel Launcher crashes are not related to this mod, since they are happening to others without the mod, and the mod is working fine on my devices running QPR2.

**Comment by jiggs82** [comment]
I'm confused you said since they are no happening to others without this mod . What do you mean? That others are having PL crashes on qpr2 without this mod ? Sorry if I sound confusing as well lol

**Comment by KieronQuinn** [comment]
There are others experiencing Pixel Launcher crashes after updating to the QPR2 beta which they fixed by uninstalling Pixel Launcher updates. Again, it's working on my devices running the beta so it's not a PLM issue.

**Comment by jiggs82** [comment]
Ok then let me try that way. Thanks

**Comment by jiggs82** [comment]
Hmm it didn't work for me. Will try other ways though

**Comment by jiggs82** [comment]
Hey @KieronQuinn it seems the only broken thing for me is the Search Box feature. No matter what widget I try to add once I apply I get PL fc's and broken gestures.

Fyi, I remember having this issue from a previous beta as well.
