### ISSUE TITLE
Icon application does not work 

### ISSUE THREAD

**Issue by pomonella01** [KieronQuinn/PixelLauncherMods#17]
I'm trying to apply an icon pack on my phone, and all goes well until I'm returned to the main screen with no changes. All the icons remain the same as they were before.
I don't know where the debug logs are, so i can't provide any at the moment, but I'll fetch them as soon as i can.

**Comment by KieronQuinn** [comment]
Does single icon replacement work in the editor?

**Comment by pomonella01** [comment]
Nope

**Comment by KieronQuinn** [comment]
And what device and firmware is this on?

**Comment by pomonella01** [comment]
Pixel 6, android 13 tiramisu beta from february with magisk installed.

**Comment by KieronQuinn** [comment]
I've no idea what's wrong then as that is identical in configuration to the device this was built on, except it was a Pixel 6 Pro. Try reinstalling maybe?

**Comment by pomonella01** [comment]
Already tried, but it didn't work. I plan to migrate back to 12 anyways since jamesDSP doesn't work, but I think it's more to do with the pixel launcher than the mods app.
Do you know where the icons database is located? I could try deleting it to force the launcher to regenerate it if that would help

**Comment by pomonella01** [comment]
I've figured out the issue! apparently changing the app grid size after applying icons will cause this problem.

**Comment by KieronQuinn** [comment]
The app is supposed to adjust to that automatically, sounds like it's got confused somewhere. Is it working now?

Also JamesDSP does work on 13, you just have to tell the installer you're using a Huawei device, as that will install the 64 bit libs that are also required on 13.

**Comment by pomonella01** [comment]
I'm currently using the stock 4x5 app grid for now and it works perfectly, I'll try to figure out some more when I get home at the end of the day. It probably did get confused somewhere, and it's probably my device being problematic.

I'll try the jamesDSP thing too, thanks!
