### ISSUE TITLE
Can't apply individual icons with icons from a certain pack if that pack wasn't already applied

### ISSUE THREAD

**Issue by Jnss98b** [KieronQuinn/PixelLauncherMods#20]
I don't know if this is a technical limitation but if I have icon packs installed and haven't applied them then I can't just replace individual icons with icons from the pack manually. I can however do that once the icon pack is applied

![image](https://user-images.githubusercontent.com/24306400/162421499-730d9712-e7a9-44bc-ba64-18838621ab74.png)
![image](https://user-images.githubusercontent.com/24306400/162421512-9a0af590-1882-4c52-a171-6edd20157789.png)

**Comment by KieronQuinn** [comment]
You are on 12 or 12L, you cannot use icon packs for themed icons on that. This isn't a bug, it's a limitation of the system.
