### ISSUE TITLE
Apps with custom icons have a border around them/ are bigger than default icons

### ISSUE THREAD

**Issue by Jnss98b** [KieronQuinn/PixelLauncherMods#21]
![Screenshot_20220409-050426_Pixel Launcher](https://user-images.githubusercontent.com/24306400/162564774-5ca4688d-32cd-42ad-9183-679d01cf8a89.png)

And I don't mean the border that surrounds suggested apps on the dock, you can clearly see a dark border around the b&o app when I closed it
![ezgif com-gif-maker](https://user-images.githubusercontent.com/24306400/162565065-d5522ea8-b87c-4971-9027-1d8a7bfd6110.gif)

What's weird too is that actionblock doesn't have a native themed icon and I just used an icon from the ondynamic pack yet when you drag it around it retains the custom icon

**Comment by KieronQuinn** [comment]
I have improved the scaling in 2.1, it now matches the sizes for legacy themed icons, icon packs and package icons for me. More changes would require modifications to the Pixel Launcher I think, so this is the best I can do.

**Comment by Jnss98b** [comment]
@KieronQuinn  I'm on the latest update and I even reset my icons and reapplied them but they still look the same with the custom icons still being as big as before. Idt it's a problem about size tho since there's a weird border around custom icons

Sync is the only custom icon applied with pixel launcher mods here
![Screenshot_20220411-024138_Pixel Launcher](https://user-images.githubusercontent.com/24306400/162679558-7f285eba-cba8-4d0e-b120-5b87b13bce7a.png)

The extra border is still there
https://user-images.githubusercontent.com/24306400/162679585-cfe8a028-675d-4360-afdb-d02805a9f58f.mp4

**Comment by KieronQuinn** [comment]
Yeah that's a known issue, no idea what causes it since PLM doesn't control the circle size of themed icons (the launcher does). Not lot I can really do, the current workaround is to simply apply a themed icon to every app (even if you're just re-applying the same icon as it has already) so they're all the same size.
