### ISSUE TITLE
Feature request : App Lock

### ISSUE THREAD

**Issue by bhaskar966** [KieronQuinn/PixelLauncherMods#23]
It's would be amazing if you can add App Lock in Pixel Launcher Mods. 

Another thing, Pixel Launcher Mods restarts launcher often , it's disabling the accessibility of Pixel Launcher DT2S . 
Is it fixable ? 
May the app need to restart launcher to work perfectly, but can you add any script to enable it automatically if it gets disabled?

**Comment by KieronQuinn** [comment]
Neither is possible, sorry.

**Comment by bhaskar966** [comment]
Okey .
Thanks 👍
