### ISSUE TITLE
Material You colors doesn't work on PE v12.1

### ISSUE THREAD

**Issue by rufus582** [KieronQuinn/PixelLauncherMods#24]
The app theme is always a purple color regardless of the current wallpaper and monet theme, on Android 12.1.
Device: Samsung M31s
Rom: Pixel Experience 12.1 v411.2 GSI
Screenshot:
![Screenshot_20220409-205608_Pixel Launcher Mods](https://user-images.githubusercontent.com/68699122/162581759-5c6b46a7-994b-4746-ab23-c943a279d213.png)

**Comment by KieronQuinn** [comment]
The colours used are loaded directly from the system, I cannot do anything if those are being reported incorrectly from the framework.

**Comment by rufus582** [comment]
Other apps are working fine tho. It's only your app that's acting wierd🥲
