### ISSUE TITLE
Latest update (2.1) creating smaller themed icons

### ISSUE THREAD

**Issue by naveenjohnsonv** [KieronQuinn/PixelLauncherMods#27]
After updating from 2.0.1 to 2.1, when I try to  pick a themed icon for my app it ends up being much smaller than it's supposed to be. Downgrading to 2.0.1 fixes this. Attaching screenshots for reference.

![2.0.1](https://i.imgur.com/RstvbHk.png)

![2.1](https://i.imgur.com/enslRRX.png)

![2.1 app drawer](https://i.imgur.com/MMxG6m5.png)

**Comment by KieronQuinn** [comment]
This is intentional, that's the size they're meant to be. 2.0 was wrong.
