### ISSUE TITLE
Magisk Module does not get reverted to stub during reset

### ISSUE THREAD

**Issue by jacob153** [KieronQuinn/PixelLauncherMods#28]
I uninstalled the magisk module > uninstalled the old version > installed the new version. The tweaks page acts like it can work and is not prompting for the magisk module to be installed and after it says it's done it just disables itself upon going back. I am on a pixel 6 android 12.

**Comment by KieronQuinn** [comment]
Run

`adb shell pm uninstall com.google.android.apps.nexuslauncher.plmoverlay`

or the same in a root shell without `adb shell`

**Comment by jacob153** [comment]
That did the trick thank you. I wonder if there is a way to automate that somewhere in the settings where you can reset everything

**Comment by KieronQuinn** [comment]
Yes, it should be automatic when resetting, that's why I'm leaving this issue open.

**Comment by KieronQuinn** [comment]
The overlay now gets reset during a reset, which as well as wiping widget replacement and hidden apps configuration, will allow it to be cleanly uninstalled in Magisk, and will offer to install again.
