### ISSUE TITLE
App doesn't work without magisk

### ISSUE THREAD

**Issue by sepehrmoh81** [KieronQuinn/PixelLauncherMods#31]
I'm currently using some other su binary and app for superuser access (phh-su to be precise) on my Huawei P10, running Pixel Experience A12.1 GSI by Ponces. The app keeps showing the loading animation forever. Is magisk a requirement for this app to work? (I'm guessing not since it's using overlays)

**Comment by KieronQuinn** [comment]
The app uses [libsu](https://github.com/topjohnwu/libsu) for its root service. I cannot guarantee support for non-Magisk su binaries, and as the app is targeted at Pixels (which will be using Magisk), supporting them is out of scope.

**Comment by sepehrmoh81** [comment]
The app's root service uses exec to run commands under root UID, right? If all comm@nds were run as root with `su -c some_command` would that fix the need for libsu? (Doesn't matter if some stuff don't work as expected)

**Comment by KieronQuinn** [comment]
No, it uses a root service, like I said. libsu uses su -c internally, but again I cannot guarantee that root services will work on other su binaries. It's not within the scope of this app either.
