### ISSUE TITLE
Applying legacy icons in app drawer

### ISSUE THREAD

**Issue by ItzDFPlayer** [KieronQuinn/PixelLauncherMods#32]
For some reason applying legacy icons in app drawer makes icons shapeless, icons applied from previous 2.0.1 version isn't bugged
![Screenshot_20220421-233444_Pixel Launcher Mods](https://user-images.githubusercontent.com/80550709/164548051-268b9c06-d109-429e-9cb5-0ec832a5aecf.png)
![Screenshot_20220421-233425_Pixel Launcher](https://user-images.githubusercontent.com/80550709/164548058-ab32d9cb-527b-430e-b87f-1471e50f8350.png)

**Comment by KieronQuinn** [comment]
Fixed in 2.2
