### ISSUE TITLE
After uninstalling the program, the system animation is abnormal

### ISSUE THREAD

**Issue by wsay-kx99** [KieronQuinn/PixelLauncherMods#36]
After clearing all modifications and uninstalling the application, when my system launcher uses the back gesture to return to the desktop, the transition animation is abnormal, and the current system is PE Plus.

https://user-images.githubusercontent.com/57807276/166397380-e536b35a-973a-4d4f-a1bd-9e9a28aa6a50.mp4

**Comment by KieronQuinn** [comment]
Not related to Pixel Launcher Mods.
