### ISSUE TITLE
Tapping on the weather temperature of the Glance widget doesn't do anything

### ISSUE THREAD

**Issue by panda4k** [KieronQuinn/PixelLauncherMods#37]
The vanilla Pixel Launcher has 2 functions when tapping on the At a glance widget. When tapped on the date, it opens google calendar and when tapping on the weather temperature it opens the google weather. This Pixel Launcher Mods doesn't open weather but it does open the calendar.

**Comment by KieronQuinn** [comment]
Pixel Launcher Mods does not modify the stock At a Glance, unless you have enabled widget replacement. This is nothing to do with PLM.

**Comment by panda4k** [comment]
Not sure what it is related to, but it doesn't work on the PLM while it does work with the Vanilla. If you have a suggestion where else I can look into it based on that, I'd appreciate it.

**Comment by KieronQuinn** [comment]
PLM **is** vanilla Pixel Launcher, it does not replace the launcher.

**Comment by panda4k** [comment]
I see where the misunderstanding is. To clarify, when using Pixel Launcher Mods, the weather stops opening when tapping on the Glance widget.

**Comment by KieronQuinn** [comment]
Again, Pixel Launcher Mods **is not its own launcher**. It is not responsible for the At a Glance widget, unless you specifically tell it to replace it. Your issue is nothing to do with PLM.
