### ISSUE TITLE
Installation failed

### ISSUE THREAD

**Issue by enskye** [KieronQuinn/PixelLauncherMods#42]
after updating from 2.0.1 to 2.2.1 I can't install Magisk module through Magisk. Magisk throws error that installation failed. tried deleting overlays without luck.

P.S. just tried to install module from 2.0.1 and installed without issues.

P.S.S. still can't install overlay. attaching logs:
https://katb.in/qutonavosup

P.S.S.S. magisk install logs:
https://www.toptal.com/developers/hastebin/ivijerifox.sql

**Comment by KieronQuinn** [comment]
Fixed in 2.2.2
