### ISSUE TITLE
Time missing from status bar in every app. (Except in noti. center)

### ISSUE THREAD

**Issue by Xerillic** [KieronQuinn/PixelLauncherMods#46]
![Screenshot_20220527-192253](https://user-images.githubusercontent.com/29320717/170799745-4507553a-20f6-4053-a7f8-2d5b0d0f9b0a.png)
![Screenshot_20220527-192109](https://user-images.githubusercontent.com/29320717/170799746-11f9bf01-5dc9-40be-a08c-f176e90e7aa5.png)
![Screenshot_20220527-192417](https://user-images.githubusercontent.com/29320717/170799784-b699399c-0132-4409-8073-5551231245de.png)

**Comment by Xerillic** [comment]
Also probably a separate issue, this doesn't change when I turn on and off the option. Even after reboot

**Comment by KieronQuinn** [comment]
#10
