### ISSUE TITLE
Feature Request: Taskbar On Android 12L Pixel

### ISSUE THREAD

**Issue by YASHKRAJ** [KieronQuinn/PixelLauncherMods#47]
Hi!
Thanks for the Pixel Launcher Mod.

Goggle introduced Taskbar in Pixel Launcher for Google Surface or it can be enabled by changing doi value to 600 on pixel devices but it'll change the whole display dpi too!

But the Taskbar feature is enabled on the Custom Pixel ROMs where just they've provided option for enabling the Taskbar without messing up with dpi.
I can provide you some Custom ROMs review link where you can see that feature live.
Can this be added from you for the Pixel Launcher?
That'd be great if this can be added in your mod so that it could be enabled in Pixel Launcher.

Thanks in advance :)

**Comment by YASHKRAJ** [comment]
1. See at timestamp 2:30
https://youtu.be/wDMzE4YMTYw

2. See timestamp at 5:15
https://youtu.be/bnafAPzsFzQ

**Comment by KieronQuinn** [comment]
Not possible without changing the whole system DPI.

**Comment by YASHKRAJ** [comment]
Oh! Well I've used that ROM and it was working without changing any dpi value!!
That's why I've even shared the clip.

**Comment by KieronQuinn** [comment]
They probably modified the launcher, this mod doesn't do that.

**Comment by YASHKRAJ** [comment]
> They probably modified the launcher, this mod doesn't do that. 

Thank for the explanation!
This cleared the issue 👍🏻

**Comment by Jnss98b** [comment]
@CodElixer Use this https://github.com/siavash79/AOSPMods

**Comment by CodElixer** [comment]
> @CodElixer Use this https://github.com/siavash79/AOSPMods

I want to use @siavash79 mod too since it's very first build😭! But I just can't because I've heard compatibility issues with Pixel Experience Plus 12.1 ROM!!😔

**Comment by siavash79** [comment]
It's now compatible with PE normal and plus

**Comment by CodElixer** [comment]
> It's now compatible with PE normal and plus 

Oh Great! So no random reboots, and no issues with Plus and AOSPMod?
