### ISSUE TITLE
Suggestion | App icon size. 

### ISSUE THREAD

**Issue by CrowleyS15** [KieronQuinn/PixelLauncherMods#5]
Would be possible for you to add the function to modify the app icon size?

**Comment by KieronQuinn** [comment]
How so? If you mean making it bigger - no, but making it smaller _might_ be possible, although it wouldn't work with themed icons.

**Comment by CrowleyS15** [comment]
Wouldn't be possible make they bigger without themed icons?

**Comment by KieronQuinn** [comment]
Nope - the icons already fill the space given if you select an icon or image that is full-width and full-height. The only way to make them bigger is to select a smaller grid size.

**Comment by CrowleyS15** [comment]
Ok, thanks anyway.
