### ISSUE TITLE
Hide apps not working on V2.2.2

### ISSUE THREAD

**Issue by daxya** [KieronQuinn/PixelLauncherMods#50]
Building XML…
Compiling resources…
sh: <stdin>[2]: /system/product/priv-app/PixelLauncherMods/lib/arm64/libaapt2.so: can't execute: Permission denied
Failed to create overlay. Build successful: false, install successful: false.

![Screenshot_20220712-193144_Pixel Launcher Mods.png](https://user-images.githubusercontent.com/52189498/178508451-0e9049fd-672b-497f-9671-7eb5034ecc45.png)

**Comment by KieronQuinn** [comment]
Your firmware is preventing execution of binaries from the app, there's nothing I can do about this.
