### ISSUE TITLE
Rkicons shows up for individual apps but not as an icon pack

### ISSUE THREAD

**Issue by Jnss98b** [KieronQuinn/PixelLauncherMods#51]
In the screenshot it shows up as Lawnicons but that's bc it's a fork of Lawnicons I believe

![Screenshot_20220719-220939](https://user-images.githubusercontent.com/24306400/179881460-82672d36-1cd1-40e3-9faf-8ba51576872a.png)
![Screenshot_20220719-220944](https://user-images.githubusercontent.com/24306400/179881485-e0a895df-b748-4eb8-b30c-3d0dd973f7b0.png)

**Comment by KieronQuinn** [comment]
Not a bug, lawnicons much like themed icons have to be applied on a icon-by-icon basis. 

And yes, if it's a fork with the same package name it will show as Lawnicons.

**Comment by Jnss98b** [comment]
Oh I didn't know they apply icons differently. Thanks for clarifying

**Comment by Jnss98b** [comment]
How come they don't show up in the themed icons selection then? Is it bc it's an android 12 limitation? That's why I assumed it applied like an icon pack @KieronQuinn
