### ISSUE TITLE
App crashes immediately

### ISSUE THREAD

**Issue by SkuxPL** [KieronQuinn/PixelLauncherMods#54]
On my s10 app crash immediately and it shows error Pixel Launcher keeps stopping. I'm using v2.3 but on older versions the error appear as well

**Comment by KieronQuinn** [comment]
Please provide a logcat and confirm that you have the Pixel Launcher installed properly.

**Comment by SkuxPL** [comment]
https://zerobin.net/?a5340ee8f626d161#0ZRPhcXQ0DC6UEZeCuWQErODwmhgcUp9ytbR7i+ydyE=

**Comment by KieronQuinn** [comment]
You don't have the Pixel Launcher installed.
