### ISSUE TITLE
[Feature request] Option to remove the status bar shadow on the home screen

### ISSUE THREAD

**Issue by Jnss98b** [KieronQuinn/PixelLauncherMods#55]
In the pixel launcher, there's a shadow under the status bar that's supposed to help with better visibility for status bar elements but the launcher just kinda blanket applies it to all wallpapers ([except for wallpapers that are light enough to activate dark texts](https://user-images.githubusercontent.com/24306400/185828115-bbb81dde-0a81-4d77-aca3-4e836aea154d.png)). It would be nice to have a toggle to remove this element from the pixel launcher

![image](https://user-images.githubusercontent.com/24306400/185828097-d0f893b0-9d63-4299-92d3-8391728e7a61.png)

**Comment by debanjan1997** [comment]
Yes need this

**Comment by KieronQuinn** [comment]
Added in 2.5
