### ISSUE TITLE
Wrong themed icon size

### ISSUE THREAD

**Issue by PoSayDone** [KieronQuinn/PixelLauncherMods#56]
After applying themed icon, icon gets bigger than others

![Screenshot_20220823-193921_Pixel Launcher Mods](https://user-images.githubusercontent.com/29358657/186187439-a2180b6a-637e-4d12-8802-c0a6827bb63b.png)
![Screenshot_20220823-194053_Pixel Launcher](https://user-images.githubusercontent.com/29358657/186187644-33c162ef-159e-41e7-85e0-f216e0b45313.png)

**Comment by KieronQuinn** [comment]
#27
