### ISSUE TITLE
UNABLE TO UNDO HIDE CLOCK ON A13

### ISSUE THREAD

**Issue by WalexjayTech** [KieronQuinn/PixelLauncherMods#57]
I can't seems to revert the Hide clock option on Android 13, the button is physically functioning but doesn't 
![Screenshot_20220824-040415](https://user-images.githubusercontent.com/59195358/186311360-52ae6377-8c09-48e0-8103-b5cbfdc96275.png)
function

**Comment by anthonyg45157** [comment]
Having this same issue. Attempt to uninstall apk and magisk as well as reinstall with no change. Can't get system clock back after hiding.

**Comment by KieronQuinn** [comment]
#10

**Comment by WalexjayTech** [comment]
Hi @anthonyg45157 

Download system UI tuner from playstore, that's what I use to fix mine

**Comment by anthonyg45157** [comment]
> Hi @anthonyg45157
> 
> Download system UI tuner from playstore, that's what I use to fix mine

Confirmed! After following the  link I decided to give that app a try and it did work.  Thanks to you and the Dev!
