### ISSUE TITLE
[ Feature Request ]  Option to force dark status bar and smartspace widget

### ISSUE THREAD

**Issue by kalkioss** [KieronQuinn/PixelLauncherMods#59]
This is a bug with Pixel launcher A13+ that it cannot detect whether the wallpaper is light enough to show dark status bar and smart space aka At a glance widget.
With some live wallpapers we get the option to force the behavior so I guess it may be possible to do the same Pixel Launcher Mods on a normal wallpaper.

**Comment by KieronQuinn** [comment]
Not possible.

**Comment by kalkioss** [comment]
Alright, thanks!
Loved the app anyways :)
