### ISSUE TITLE
App working partially 

### ISSUE THREAD

**Issue by mjain234** [KieronQuinn/PixelLauncherMods#61]
I m on Pixel Launcher and when I installed this pixel Launcher mod apk, half of the tjings are not working as you can see in the [video ](https://user-images.githubusercontent.com/70900505/192990347-0fd228d2-273c-40fd-8d02-80cb54a88c82.mp4). It just stays there only for a while and no change after that.

Android version - Android 13
Device - Realme 2 Pro
ROM - Arrow OS

**Comment by KieronQuinn** [comment]
There is very little I can do about the app not working properly on specific devices with specific ROMs. I do not have access to this device to debug, and PLM is intended for use on Pixels, I cannot guarantee it will work on every device.
