### ISSUE TITLE
When opening recents with transparent background, the current app is blurred.

### ISSUE THREAD

**Issue by Drazini** [KieronQuinn/PixelLauncherMods#63]
If you open the recents menu from an app then that app will be blurred as well as the background, when only the background should be blurred. If you click any of the interactive elements (select, screenshot, link, image, etc.) in recents the app will un-blur itself and look as it should. Screenshots attached of the current apl blurred and not blurred (entering recents from app vs from home screen)
![Screenshot_20220930-042109](https://user-images.githubusercontent.com/20171307/193259037-992d52a9-5cbd-43f2-bec4-2eff267c9f86.png)
![Screenshot_20220930-042101](https://user-images.githubusercontent.com/20171307/193259056-255d3a88-14d8-4362-979c-bb8aa158a841.png)

**Comment by KieronQuinn** [comment]
This is caused by the transparent background option, I can't do anything about it.
