### ISSUE TITLE
Manually added themed icons do not follow theme in animations

### ISSUE THREAD

**Issue by Drazini** [KieronQuinn/PixelLauncherMods#64]
When icons are animated when opening or closing apps, those which have themed icons natively or implemented through something such as AOSP mods will follow their custom icons during animations, however apps that are manually changed through pixel launcher mods do not follow their themed appearance and pop to their normal icon during animations.

**Comment by KieronQuinn** [comment]
This is normal, adaptive icons get dynamically reloaded when they're moved in order to perform the animations cannot be themed.

**Comment by KrazyLurt** [comment]
Is there a way to have custom icons without this issue? I have built my own custom icon pack and on other launchers there are a way bot to have it switching during closing animations.

**Comment by KieronQuinn** [comment]
No, this is a limitation of the launcher. Nothing can be done.

**Comment by KrazyLurt** [comment]
Okay, thanks for the quick response 👍 , that's really unfortunate 😕

**Comment by xingpingcn** [comment]
> This is normal, adaptive icons get dynamically reloaded when they're moved in order to perform the animations cannot be themed.

but why some themed app icons will not exist this
