### ISSUE TITLE
Clock on the status bar disappeared

### ISSUE THREAD

**Issue by steve1145114** [KieronQuinn/PixelLauncherMods#67]
I have switched off the "Hide Clock",but the clock still disappear from my status bar!
![Screenshot_20221007-003842](https://user-images.githubusercontent.com/89009827/194370318-6f465904-6a9c-40f3-970f-ae210acbc463.png)

**Comment by steve1145114** [comment]
On Android 13 (TP1A.220624.014)

**Comment by KieronQuinn** [comment]
#10
