### ISSUE TITLE
[issue] icons from icon packs not rendering correctly

### ISSUE THREAD

**Issue by skridofly** [KieronQuinn/PixelLauncherMods#68]
If I want to set an icon from an icon pack for an app it simplywill be rendered as a grey circle. I am rooted and have given the pixel launcher mod root acces.
![bug report](https://user-images.githubusercontent.com/115251455/195662590-86e6a5db-64fa-4dd4-b924-c9eaf1455889.jpg)

**Comment by KieronQuinn** [comment]
Are you trying to select a themed icon here?

**Comment by skridofly** [comment]
Here is a video of what I am trying to do

https://user-images.githubusercontent.com/115251455/195667986-aa73cba4-f908-47f1-8798-fd0eae5cc06b.mp4

**Comment by skridofly** [comment]
But how come that that exact method has worked with that same app before?
