### ISSUE TITLE
Causing launcher to crash 

### ISSUE THREAD

**Issue by Naveed-SNR** [KieronQuinn/PixelLauncherMods#69]
When swiping on the home screen to switch pages, pixel launcher keeps crashing. And it also crashes when I try to put a widget on the home screen.

Crash log URL:
https://paste.evolution-x.org/Vh8tLW

**Comment by KieronQuinn** [comment]
Which Android version and which Pixel Launcher version?

**Comment by Naveed-SNR** [comment]
> Which Android version and which Pixel Launcher version? 

I'm on EvolutionX (Android 13) and Pixel Launcher 13.

**Comment by rakib-rock** [comment]
I'm facing same crush problem on Spark Os Android 13

**Comment by KieronQuinn** [comment]
Which module was it if you don't mind me asking?

**Comment by Naveed-SNR** [comment]
> Which module was it if you don't mind me asking? 

It's an outdated lsposed module "Hide Pixel Launcher Date". 

(Package name: com.yuanwofei.PixelLauncher

I used ot remove at a glance since I can't remove both the search bar and At a glance widget simultaneously using Pixel Launcher Mods.

)

**Comment by KieronQuinn** [comment]
Yep, that'll do it. You can't remove Smartspace (the date) anymore, it has to be hidden - PLM does this when doing the overlay.
