### ISSUE TITLE
[Android 13] App doesn't require the Magisk module

### ISSUE THREAD

**Issue by billal78** [KieronQuinn/PixelLauncherMods#70]
On Android 13 : When i go in the "At a glance" section of the app, the app doesn't ask me to download the Magisk module but it allows me to directly enable the replacement with the Switch button.
Though, after enabling the replacement and after clicking on the apply and close buttons, the Enable Replacement switch becomes unchecked and the "At a glance" replacement doesn't work

https://user-images.githubusercontent.com/77847142/197528013-07f6e87c-9327-4c90-9b89-dd68fcff271a.mp4

**Comment by KieronQuinn** [comment]
Have you previously used the module, or are you using a ROM that has the app bundled? The app looks for the existence of the overlay, it should not be possible for those options to appear without the overlay existing.

**Comment by billal78** [comment]
I am on a fresh installation (installed it 3 days ago) of Pixel OS on a Xiaomi phone
So i have never used the module, though, i installed this Magisk mod https://www.pling.com/p/1915907/ but i uninstalled it as you can see ![Screenshot_20221024-155548.png](https://user-images.githubusercontent.com/77847142/197543688-7a935467-f0c9-4f20-8657-fb218676d9b3.png)

**Comment by billal78** [comment]
Works perfectly, thanks ![Screenshot_20221024-162153.png](https://user-images.githubusercontent.com/77847142/197549261-2c192c02-e69b-4d2b-af74-96e5b9d17b31.png)
