### ISSUE TITLE
Custom icon glitch 

### ISSUE THREAD

**Issue by dimasmaniac10** [KieronQuinn/PixelLauncherMods#72]
![Screenshot_20221025-194336](https://user-images.githubusercontent.com/85919955/197764707-37d3a90e-e3ce-4ea4-b11f-f07eb322ac7e.png)

![Screenshot_20221025-194545_Pixel_Launcher_Mods](https://user-images.githubusercontent.com/85919955/197765065-99ea2597-1a04-4760-8300-bab99b18d6ce.png)
Glitchy icon when using custom icon on Android 13

**Comment by KieronQuinn** [comment]
Please send the icon pack or icon you're using so I can try to reproduce it.

**Comment by dimasmaniac10** [comment]
It's from rom though.. so it's "Themed icon (Legacy)" one..
I'm using PixelOS

**Comment by KieronQuinn** [comment]
Almost definitely a mismatch of Pixel Launcher versions then. Nothing I can do, Google changed the icon format.
