### ISSUE TITLE
It's loading all the time.

### ISSUE THREAD

**Issue by BuaGAAA** [KieronQuinn/PixelLauncherMods#75]
Sorry to disturb you. 
A short time ago, when I was using Crdroid 8.5(Android 12), I installed the seamless magisk module and decided to install Pixel Launcher mods. But when I rebooted my device,I found that it didn't work at all. It showed "loading apps/shortcuts" (I've given the root access.)

Now I'm using the Pixel Experience 's GSI (Android 13)( the system includes Pixel launcher ). When I installed the app (or magisk module), I found it still doesn't work （it has been confirmed to get root access）😂. It shows the words: loading apps/shortcuts over and over again. It seems that the app will never get the information from my Pixel Launcher.
I hope you can help me 🥲
Wish you have a good day!

**Comment by KieronQuinn** [comment]
If this is still happening, please provide a log.

**Comment by KieronQuinn** [comment]
No log provided in over a year, closing.
