### ISSUE TITLE
Crashing on start

### ISSUE THREAD

**Issue by pawiond** [KieronQuinn/PixelLauncherMods#76]
Crashing on Android 12 realme ui

**Comment by KieronQuinn** [comment]
Please provide a log.

**Comment by pawiond** [comment]
How can i provide log when app not opening

**Comment by KieronQuinn** [comment]
https://www.xda-developers.com/how-to-take-logs-android/

A system log is what is required.

**Comment by rayhan999** [comment]
Hello, I'm facing the same issue on my Derpfest a13 rom.
Here's the log: [https://bin.kv2.dev/~63f08aafe599576ea02bbaed](https://bin.kv2.dev/~63f08aafe599576ea02bbaed?fbclid=IwAR2cQn5_BXCc-cOgzdEWFDX5abXKdRq1QRSgEUjvQATjaH51CNkwj4GSDa0)

**Comment by KieronQuinn** [comment]
> Hello, I'm facing the same issue on my Derpfest a13 rom. Here's the log: [https://bin.kv2.dev/~63f08aafe599576ea02bbaed](https://bin.kv2.dev/~63f08aafe599576ea02bbaed?fbclid=IwAR2cQn5_BXCc-cOgzdEWFDX5abXKdRq1QRSgEUjvQATjaH51CNkwj4GSDa0)

You do not have the Pixel Launcher installed.
