### ISSUE TITLE
complete loss of hours

### ISSUE THREAD

**Issue by sweetybondar** [KieronQuinn/PixelLauncherMods#77]
![Screenshot_20221117-002221_Браузер Альфа](https://user-images.githubusercontent.com/104734219/202297292-92f63b67-c38a-4f9a-bd1b-94b9c4e159b9.png)
Full cleaning according to the developer's instructions does not help to return the clock, and reboot, and deleting all launcher data, and updating, nothing helps to return the clock

**Comment by KieronQuinn** [comment]
#10
