### ISSUE TITLE
[Request] Option to hide search box

### ISSUE THREAD

**Issue by SosPosos** [KieronQuinn/PixelLauncherMods#78]
Please, add an option to hide search box.. maybe you can just add a blank widget.
![IMG_20221118_102953_535](https://user-images.githubusercontent.com/52379151/202646103-1ad3736c-8d2c-469a-bdfc-2792887d7097.jpg)

**Comment by K-plus69** [comment]
If you have installed Chrome, replace the bottom bar with the chrome dino widget. It actually removed the bar completely

**Comment by KieronQuinn** [comment]
Added a blank widget in 2.5
