### ISSUE TITLE
Factory reset

### ISSUE THREAD

**Issue by naixx** [KieronQuinn/PixelLauncherMods#81]
I almost turned gray when used this mod.

Probably the issue is that I'm on 12b5 or something went wrong but when I enabled replacement of at a glance without any widget and restarted, pixel launcher started to crash and auto restart to make factory reset. I wasn't ready to loose all my data.

Thankfully notification area was available, so that I managed to open mods app and disable that feature. The problem was that there was some timeout of 5-7 seconds between restart and launcher crash and phone went on another factory reset request and restart loop.

**Comment by KieronQuinn** [comment]
You don't need to reset to disable a Magisk module, you can use Magisk safe mode or ADB. There is always a risk of crashes when using mods, if you can get a logcat I can maybe fix it but otherwise there's nothing I can do.
