### ISSUE TITLE
Themed Icons applied over app don't change color when background changes

### ISSUE THREAD

**Issue by flawnn** [KieronQuinn/PixelLauncherMods#83]
Anyone have a fix for this? I use a live wallpaper where colors change once in a while but the icons don't seem to keep up.

**Comment by red0fireus** [comment]
I have the same issue

**Comment by flawnn** [comment]
It's super weird definitely. If I set the themed icons by hand in the Pixel Launcher Mods app, it works and actually is a dynamic theme icon...

**Comment by KieronQuinn** [comment]
If you're setting a themed icon, you're letting the system handle the colours. The dynamic colour changing of the main ("app drawer") icon is only updated when the system notifies of a colour change, and can be delayed depending on the wallpaper.

**Comment by flawnn** [comment]
> If you're setting a themed icon, you're letting the system handle the colours. The dynamic colour changing of the main ("app drawer") icon is only updated when the system notifies of a colour change, and can be delayed depending on the wallpaper.

Ah, I see. Would having only applying Icon Packs to Home Screen Icons be something that is worth adding in the next version? Or at least, having the home screen icons being handled by the system.
