### ISSUE TITLE
Some icons revert back to stock when using icon packs

### ISSUE THREAD

**Issue by aliantonio** [KieronQuinn/PixelLauncherMods#84]
Some icons revert back to the stock icons when using an icon pack. When I reapply icons, it works but then reverts back after a short time.

Pixel 7
Pix Material You icon pack

**Comment by KieronQuinn** [comment]
This is normal, icons get reset by the launcher. Make sure you have Seamless Restart set to the recommended level or higher, beyond that there's nothing I can do.
