### ISSUE TITLE
Home screen appears in recent 

### ISSUE THREAD

**Issue by khaled-0** [KieronQuinn/PixelLauncherMods#87]
This happens when using transparent app switcher with any 3rd party launchers.
Doesn't happen with Pixel Launcher
Doesn't happen when not using transparency.
![image](https://user-images.githubusercontent.com/74397286/210542372-58624c19-d7a0-4379-8026-8c4e3d527a91.png)

**Comment by KieronQuinn** [comment]
Nothing I can do about this, PLM can't modify Pixel Launcher code.
