### ISSUE TITLE
wechat icon have something wrong in pixel7pro

### ISSUE THREAD

**Issue by hongfa1380** [KieronQuinn/PixelLauncherMods#89]
![Screenshot_20230108-100305](https://user-images.githubusercontent.com/49623327/211177497-252dfbec-d3d2-48c8-ac21-b87b1301710b.png)
here is good

![Screenshot_20230108-100322](https://user-images.githubusercontent.com/49623327/211177498-6d3feef5-44e0-482c-be2b-5fe21e84bad1.png)
here is wrong

![Screenshot_20230107-235222](https://user-images.githubusercontent.com/49623327/211177517-aee44d1e-d5b2-4638-abd8-61a70b343347.png)

**Comment by HOCC2011** [comment]
I have the same problem on my pixel 7, and even when I re-apply themed icons on app that support it

before:
![Screenshot_20230717-001300.png](https://github.com/KieronQuinn/PixelLauncherMods/assets/92627916/0bd1eb65-e340-48bc-aff7-a1f6c797d6bd)

after:
![Screenshot_20230717-001305.png](https://github.com/KieronQuinn/PixelLauncherMods/assets/92627916/a7924d24-3b9f-4aad-a503-7dab9791f949)

**Comment by TheShark27** [comment]
Same here. The icon appears cropped for some reason, it's the case with a lot of the icons I have.

**Comment by b-risk** [comment]
Yep, cropped for many of my icons

**Comment by Fefedu973** [comment]
Same here

**Comment by KieronQuinn** [comment]
Cleanup closing in favour of #74 as it's the same request
