### ISSUE TITLE
Hide apps not working 

### ISSUE THREAD

**Issue by mjain234** [KieronQuinn/PixelLauncherMods#91]
I have recently flashed pixel launcher mods which comes with pixel launcher extended magisk module and been trying to hide apps  but it isn't working somehow as you can see [here](https://user-images.githubusercontent.com/70900505/215146711-d37181ef-a878-4f3e-b19b-2fb41d4accec.mp4). Am I doing something wrong here?

Device ~ Realme 2 Pro

Android version ~ Android 13

ROM ~ Arrow OS

**Comment by KieronQuinn** [comment]
Are you using widget replacement too? That crashes on current A13 builds I think.

**Comment by mjain234** [comment]
I didn't get you, widget replacement??

**Comment by KieronQuinn** [comment]
The at a glance / search box replacement option, which replaces it with a widget. Both of these features use overlays.

**Comment by mjain234** [comment]
> The at a glance / search box replacement option, which replaces it with a widget. Both of these features use overlays. 

Nope, it's already disabled.

**Comment by KieronQuinn** [comment]
Ok, in that case please provide a log of it crashing.

**Comment by KieronQuinn** [comment]
No log provided, closing
