### ISSUE TITLE
App doesn't detect Root provided by KernelSU method 

### ISSUE THREAD

**Issue by drkhemu** [KieronQuinn/PixelLauncherMods#92]
Hello sir,
I was trying to use this app and it was asking for root.
I am using KernelSU root method at present.
Though other app detect root without any problem, when I tried to allow root for pixel launcher mod it was not detected

Pls help in this issue !! I can provide and info u required

Thanks n regards

**Comment by KieronQuinn** [comment]
[The root check is done by a simple "whoami" via libsu](https://github.com/KieronQuinn/PixelLauncherMods/blob/43cd682a5829d071e21348db77d9a7fcc0afb154/app/src/main/java/com/kieronquinn/app/pixellaunchermods/repositories/RootServiceRepository.kt#L41). If that's not working, it's not under the control of PLM.
