### ISSUE TITLE
Can't access hidden apps

### ISSUE THREAD

**Issue by ArhamQureshi6** [KieronQuinn/PixelLauncherMods#93]
What is the use of hidden apps if I can't access it
Normally there are gesture to access it but there isn't any on this launcher mod.
This is completely useless.
Please change my mind

**Comment by KieronQuinn** [comment]
Hide apps hides apps. It doesn't obscure them, it's not possible for a mod to do that. It's for apps you want to keep installed, but never launch, like icon packs or bloatware you can't uninstall.

**Comment by KieronQuinn** [comment]
> @KieronQuinn, there still is a use case where people may want to access hidden apps.
> 
> Perhaps to ability to launch the apps from inside the Pixel Launcher like [Pixel Mods](https://forum.xda-developers.com/t/pixel-mods-hide-apps-from-the-pixel-launcher-xposed.4288973/)?

It's not possible for an overlay to do that. Use the Xposed module you linked if you need that functionality
