### ISSUE TITLE
Empty spaces in search after hiding app

### ISSUE THREAD

**Issue by shivanshvermak** [KieronQuinn/PixelLauncherMods#95]
![Screenshot_20230219-103206](https://user-images.githubusercontent.com/15206857/219923276-bd41369f-206e-408d-a5f7-9b9e9a4c4557.png)
I hid YouTube and this is what it appears when I search "YouTube". Can this be fixed?

**Comment by KieronQuinn** [comment]
No, can't be fixed with just overlays. An Xposed module would be required for this.
